[package]
name = "rbfmt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
getopts = "0.2.21"
prism = { package = "ruby-prism", version = "0.24.0" }

[dev-dependencies]
similar-asserts = "1.5.0"
