[package]
name = "rubyfmt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lib-ruby-parser = "4.0.5"

[dev-dependencies]
pretty_assertions = "1.4.0"
